#!/bin/sh
# xrandr --output DP-3 --mode "1920x1080" --rate 79.95 --left-of DP-0
# Extend display
xrandr --output HDMI-0 --mode "1920x1080" --rate 180.00 --primary
xinput set-prop 11 "Coordinate Transformation Matrix" 0.2 0.0 0.0 0.0 0.2 0.0 0 0 1
xinput set-prop 13 "Coordinate Transformation Matrix" 0.2 0.0 0.0 0.0 0.2 0.0 0 0 1
xinput set-prop 9 "Coordinate Transformation Matrix" 0.2 0.0 0.0 0.0 0.2 0.0 0 0 1
xinput set-prop 15 "Coordinate Transformation Matrix" 0.2 0.0 0.0 0.0 0.2 0.0 0 0 1
xinput set-prop 10 "Coordinate Transformation Matrix" 0.2 0.0 0.0 0.0 0.2 0.0 0 0 1
